//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToDoDataModelContainer : DbContext
    {
        public ToDoDataModelContainer()
            : base("name=ToDoDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<user> users { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<achivement> achivements { get; set; }
        public DbSet<reminder> reminders { get; set; }
    }
}
