//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Items = new HashSet<todo_item>();
            this.Achivements = new HashSet<achivement>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password_hash { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public AccessLevel access_level { get; set; }
    
        public virtual ICollection<todo_item> Items { get; set; }
        public virtual ICollection<achivement> Achivements { get; set; }
    }
}
