//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Tasks = new HashSet<task>();
            this.Achivements = new HashSet<achivement>();
            this.Friends = new HashSet<user>();
            this.Reminders = new HashSet<reminder>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password_hash { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public AccessLevel access_level { get; set; }
        public string phone_number { get; set; }
    
        public virtual ICollection<task> Tasks { get; set; }
        public virtual ICollection<achivement> Achivements { get; set; }
        public virtual ICollection<user> Friends { get; set; }
        public virtual ICollection<reminder> Reminders { get; set; }
    }
}
